# ⚒ Week 4: Team Project — Student Performance Analysis

## 🧠 Goal
This week, you are working as a team.

Each group has a responsibility.
Each group must complete their work before the next group continues.

---

## 🏗 Project Flow

Raw Data → Cleaning → Analysis → Insight

---

## ⚠️ Important Rules

- Everyone must contribute
- Juniors must write code (not just watch)
- Core members must guide juniors
- You must understand your code

# Section 0 - Overview

This project is divided into 3 groups:

1. Cleaning
2. Analysis
3. Insight

Each group must complete their section before the next begins.

# SECTION 1 — Understanding the Dataset

### What is this dataset about?

- What type of data is present?
- What are the columns?
- What might we analyze?

# SECTION 2 — Load Dataset

In [7]:
import pandas as pd

df = pd.read_csv("../../data/StudentsPerformance.csv")

df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

# SECTION 3 — Basic Exploration

In [3]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   str
 1   race/ethnicity               1000 non-null   str
 2   parental level of education  1000 non-null   str
 3   lunch                        1000 non-null   str
 4   test preparation course      1000 non-null   str
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), str(5)
memory usage: 62.6 KB

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

# SECTION 4 — Cleaning Task
Task:
Check for missing values
Fix or remove them

Hint:

In [ ]:
df.isnull().sum()

# ⚒ ROLE-BASED TASKS

## CLEANING GROUP

Goal:
Clean the dataset so it can be used for analysis.

Deliverable:
A cleaned dataset

Tasks:

### Core :

👉 Decide how to handle missing values:
- remove rows OR
- fill missing values

### Junior :

👉 Print columns that have missing values

👉 Count total missing values

#### Code Hints:

In [8]:
df.dropna()
df.fillna()
df.dtypes

TypeError: NDFrame.fillna() missing 1 required positional argument: 'value'

### Output:
Save cleaned dataset as:
 cleaned_data.csv

In [ ]:
df.to_csv("cleaned_data.csv", index=False)

## ANALYSIS GROUP

Goal:
Use cleaned data to calculate insights

##### IMPORTANT: 
Only start AFTER cleaned_data.csv is ready

##### Load cleaned dataset:

In [9]:
df = pd.read_csv("cleaned_data.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'cleaned_data.csv'

Tasks:

* Core :

👉 Find average math score

👉 Find average reading score

👉 Find average writing score
* Junior :

👉 Count how many students passed math (>= 50)

👉 Loop through scores and print "Pass" or "Fail"

In [ ]:
math_scores = df["math score"]
for scores in math_scores:
    if scores >= 50:
        print ("pass")
        pass_count += 1
    else:
        print ("fail")
print ("Total passed:", pass_count)

""" for scores in math_scores:
    if scores >= 50:
        print ("pass")
    else: print ("fail") """

pass
pass
pass
fail
pass
pass
pass
fail
pass
fail
pass
fail
pass
pass
pass
pass
pass
fail
fail
pass
pass
pass
fail
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
fail
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
fail
pass
pass
pass
fail
pass
fail
pass
pass
pass
pass
fail
pass
pass
fail
pass
pass
fail
pass
fail
fail
fail
pass
pass
pass
fail
fail
pass
pass
fail
pass
pass
pass
pass
pass
pass
fail
pass
fail
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
fail
pass
pass
fail
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
fail
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
fail
pass
fail
pass
pass
pass
pass
fail
pass
pass
fail
pass
pass
pass
fail
pass
pass
pass
pass
pass
pass
pass
pass
pass
fail
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
fail
fail
pass
pass
pass
pass
fail
pass
pass
pass
pass
pass
pass
pass
fail
pass
pass
pass
pass
pass
fail
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
fail
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
fail
pass
pass
pass
pass
pass
pass
pass
pass
pass
fail
pass
pass
pass
pass
pass
pass
pass
pass
fail
pass
pass
fail
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
fail
pass
fail
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
fail
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
fail
fail
pass
pass
fail
pass
fail
pass
fail
pass
pass
pass
pass
pass
fail
fail
fail
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
fail
pass
pass
pass
fail
pass
pass
pass
pass
pass
fail
pass
fail
pass
pass
fail
pass
pass
fail
pass
pass
pass
fail
pass
pass
pass
pass
pass
pass
pass
fail
fail
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
fail
pass
pass
pass
pass
pass
pass
fail
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
fail
pass
fail
pass
pass
pass
pass
pass
pass
pass
pass
fail
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
fail
pass
pass
pass
pass
pass
pass
fail
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
fail
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
fail
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
fail
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
fail
fail
pass
pass
fail
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
fail
pass
pass
fail
pass
pass
pass
pass
pass
pass
pass
pass
fail
fail
pass
pass
pass
pass
pass
pass
pass
pass
pass
fail
pass
pass
fail
pass
pass
pass
pass
pass
pass
pass
pass
fail
pass
fail
pass
pass
pass
pass
pass
pass
fail
pass
pass
pass
pass
fail
pass
pass
pass
pass
pass
fail
pass
pass
pass
pass
pass
pass
pass
pass
fail
pass
pass
pass
fail
pass
pass
pass
pass
pass
pass
pass
fail
fail
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
fail
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
fail
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
fail
pass
pass
pass
pass
pass
pass
fail
pass
pass
pass
fail
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
fail
pass
pass
fail
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
fail
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
fail
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
fail
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
fail
pass
fail
pass
pass
fail
pass
pass
pass
pass
fail
pass
fail
pass
pass
fail
pass
pass
pass
fail
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
fail
pass
pass
pass
fail
pass
pass
pass
pass
fail
pass
pass
pass
pass
pass
fail
pass
fail
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
fail
pass
fail
pass
fail
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
fail
pass
pass
pass
pass
pass
pass
fail
pass
pass
pass
pass
fail
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
fail
pass
pass
pass
pass
pass
fail
fail
pass
pass
pass
pass
pass
fail
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
fail
fail
pass
pass
fail
pass
pass
pass
fail
pass
pass
pass
pass
pass
pass
fail
fail
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
fail
fail
pass
pass
pass
pass
pass
pass
pass
pass
pass
fail
pass
pass
fail
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
fail
pass
pass
pass
pass
pass
pass
fail
pass
pass
pass
pass
pass
fail
pass
fail
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
pass
Total passed: 865

' for scores in math_scores:\n    if scores >= 50:\n        print ("pass")\n    else: print ("fail") '

In [10]:
pass_count = 0
math_scores = df ["math score"]. to_list()
for i, score in enumerate (math_scores,start=1):
    if score >= 50:
       print ("student" , i, "Passed")
       pass_count +=1
    else:
        print (("student"),i , "Failed")
print ("Total passed:",pass_count)

student 1 Passed
student 2 Passed
student 3 Passed
student 4 Failed
student 5 Passed
student 6 Passed
student 7 Passed
student 8 Failed
student 9 Passed
student 10 Failed
student 11 Passed
student 12 Failed
student 13 Passed
student 14 Passed
student 15 Passed
student 16 Passed
student 17 Passed
student 18 Failed
student 19 Failed
student 20 Passed
student 21 Passed
student 22 Passed
student 23 Failed
student 24 Passed
student 25 Passed
student 26 Passed
student 27 Passed
student 28 Passed
student 29 Passed
student 30 Passed
student 31 Passed
student 32 Passed
student 33 Passed
student 34 Failed
student 35 Passed
student 36 Passed
student 37 Passed
student 38 Passed
student 39 Passed
student 40 Passed
student 41 Passed
student 42 Passed
student 43 Passed
student 44 Passed
student 45 Passed
student 46 Passed
student 47 Passed
student 48 Passed
student 49 Passed
student 50 Passed
student 51 Passed
student 52 Passed
student 53 Passed
student 54 Passed
student 55 Passed
student 56 Failed
student 57 Passed
student 58 Passed
student 59 Passed
student 60 Failed
student 61 Passed
student 62 Failed
student 63 Passed
student 64 Passed
student 65 Passed
student 66 Passed
student 67 Failed
student 68 Passed
student 69 Passed
student 70 Failed
student 71 Passed
student 72 Passed
student 73 Failed
student 74 Passed
student 75 Failed
student 76 Failed
student 77 Failed
student 78 Passed
student 79 Passed
student 80 Passed
student 81 Failed
student 82 Failed
student 83 Passed
student 84 Passed
student 85 Failed
student 86 Passed
student 87 Passed
student 88 Passed
student 89 Passed
student 90 Passed
student 91 Passed
student 92 Failed
student 93 Passed
student 94 Failed
student 95 Passed
student 96 Passed
student 97 Passed
student 98 Passed
student 99 Passed
student 100 Passed
student 101 Passed
student 102 Passed
student 103 Passed
student 104 Passed
student 105 Passed
student 106 Passed
student 107 Passed
student 108 Passed
student 109 Passed
student 110 Passed
student 111 Passed
student 112 Passed
student 113 Passed
student 114 Passed
student 115 Passed
student 116 Passed
student 117 Passed
student 118 Passed
student 119 Passed
student 120 Passed
student 121 Passed
student 122 Passed
student 123 Passed
student 124 Passed
student 125 Passed
student 126 Passed
student 127 Passed
student 128 Passed
student 129 Passed
student 130 Passed
student 131 Passed
student 132 Passed
student 133 Passed
student 134 Passed
student 135 Passed
student 136 Passed
student 137 Passed
student 138 Passed
student 139 Passed
student 140 Passed
student 141 Passed
student 142 Passed
student 143 Failed
student 144 Passed
student 145 Passed
student 146 Failed
student 147 Passed
student 148 Passed
student 149 Passed
student 150 Passed
student 151 Passed
student 152 Passed
student 153 Passed
student 154 Passed
student 155 Passed
student 156 Passed
student 157 Passed
student 158 Passed
student 159 Passed
student 160 Passed
student 161 Passed
student 162 Passed
student 163 Failed
student 164 Passed
student 165 Passed
student 166 Passed
student 167 Passed
student 168 Passed
student 169 Passed
student 170 Passed
student 171 Passed
student 172 Passed
student 173 Passed
student 174 Passed
student 175 Failed
student 176 Passed
student 177 Failed
student 178 Passed
student 179 Passed
student 180 Passed
student 181 Passed
student 182 Failed
student 183 Passed
student 184 Passed
student 185 Failed
student 186 Passed
student 187 Passed
student 188 Passed
student 189 Failed
student 190 Passed
student 191 Passed
student 192 Passed
student 193 Passed
student 194 Passed
student 195 Passed
student 196 Passed
student 197 Passed
student 198 Passed
student 199 Failed
student 200 Passed
student 201 Passed
student 202 Passed
student 203 Passed
student 204 Passed
student 205 Passed
student 206 Passed
student 207 Passed
student 208 Passed
student 209 Passed
student 210 Passed
student 211 Passed
student 212 Failed
student 213 Failed
student 214 Passed
student 215 Passed
student 216 Passed
student 217 Passed
student 218 Failed
student 219 Passed
student 220 Passed
student 221 Passed
student 222 Passed
student 223 Passed
student 224 Passed
student 225 Passed
student 226 Failed
student 227 Passed
student 228 Passed
student 229 Passed
student 230 Passed
student 231 Passed
student 232 Failed
student 233 Passed
student 234 Passed
student 235 Passed
student 236 Passed
student 237 Passed
student 238 Passed
student 239 Passed
student 240 Passed
student 241 Passed
student 242 Passed
student 243 Passed
student 244 Passed
student 245 Passed
student 246 Passed
student 247 Passed
student 248 Passed
student 249 Passed
student 250 Passed
student 251 Failed
student 252 Passed
student 253 Passed
student 254 Passed
student 255 Passed
student 256 Passed
student 257 Passed
student 258 Passed
student 259 Passed
student 260 Passed
student 261 Passed
student 262 Passed
student 263 Failed
student 264 Passed
student 265 Passed
student 266 Passed
student 267 Passed
student 268 Passed
student 269 Passed
student 270 Passed
student 271 Passed
student 272 Passed
student 273 Failed
student 274 Passed
student 275 Passed
student 276 Passed
student 277 Passed
student 278 Passed
student 279 Passed
student 280 Passed
student 281 Passed
student 282 Failed
student 283 Passed
student 284 Passed
student 285 Failed
student 286 Passed
student 287 Passed
student 288 Passed
student 289 Passed
student 290 Passed
student 291 Passed
student 292 Passed
student 293 Passed
student 294 Passed
student 295 Passed
student 296 Passed
student 297 Failed
student 298 Passed
student 299 Failed
student 300 Passed
student 301 Passed
student 302 Passed
student 303 Passed
student 304 Passed
student 305 Passed
student 306 Passed
student 307 Passed
student 308 Passed
student 309 Passed
student 310 Failed
student 311 Passed
student 312 Passed
student 313 Passed
student 314 Passed
student 315 Passed
student 316 Passed
student 317 Passed
student 318 Passed
student 319 Passed
student 320 Passed
student 321 Passed
student 322 Passed
student 323 Passed
student 324 Failed
student 325 Failed
student 326 Passed
student 327 Passed
student 328 Failed
student 329 Passed
student 330 Failed
student 331 Passed
student 332 Failed
student 333 Passed
student 334 Passed
student 335 Passed
student 336 Passed
student 337 Passed
student 338 Failed
student 339 Failed
student 340 Failed
student 341 Passed
student 342 Passed
student 343 Passed
student 344 Passed
student 345 Passed
student 346 Passed
student 347 Passed
student 348 Passed
student 349 Passed
student 350 Passed
student 351 Passed
student 352 Passed
student 353 Passed
student 354 Failed
student 355 Passed
student 356 Passed
student 357 Passed
student 358 Failed
student 359 Passed
student 360 Passed
student 361 Passed
student 362 Passed
student 363 Passed
student 364 Failed
student 365 Passed
student 366 Failed
student 367 Passed
student 368 Passed
student 369 Failed
student 370 Passed
student 371 Passed
student 372 Failed
student 373 Passed
student 374 Passed
student 375 Passed
student 376 Failed
student 377 Passed
student 378 Passed
student 379 Passed
student 380 Passed
student 381 Passed
student 382 Passed
student 383 Passed
student 384 Failed
student 385 Failed
student 386 Passed
student 387 Passed
student 388 Passed
student 389 Passed
student 390 Passed
student 391 Passed
student 392 Passed
student 393 Passed
student 394 Passed
student 395 Passed
student 396 Failed
student 397 Passed
student 398 Passed
student 399 Passed
student 400 Passed
student 401 Passed
student 402 Passed
student 403 Failed
student 404 Passed
student 405 Passed
student 406 Passed
student 407 Passed
student 408 Passed
student 409 Passed
student 410 Passed
student 411 Passed
student 412 Passed
student 413 Passed
student 414 Passed
student 415 Passed
student 416 Passed
student 417 Passed
student 418 Passed
student 419 Passed
student 420 Passed
student 421 Passed
student 422 Passed
student 423 Failed
student 424 Passed
student 425 Failed
student 426 Passed
student 427 Passed
student 428 Passed
student 429 Passed
student 430 Passed
student 431 Passed
student 432 Passed
student 433 Passed
student 434 Failed
student 435 Passed
student 436 Passed
student 437 Passed
student 438 Passed
student 439 Passed
student 440 Passed
student 441 Passed
student 442 Passed
student 443 Passed
student 444 Passed
student 445 Passed
student 446 Passed
student 447 Passed
student 448 Passed
student 449 Failed
student 450 Passed
student 451 Passed
student 452 Passed
student 453 Passed
student 454 Passed
student 455 Passed
student 456 Failed
student 457 Passed
student 458 Passed
student 459 Passed
student 460 Passed
student 461 Passed
student 462 Passed
student 463 Passed
student 464 Passed
student 465 Passed
student 466 Passed
student 467 Failed
student 468 Passed
student 469 Passed
student 470 Passed
student 471 Passed
student 472 Passed
student 473 Passed
student 474 Passed
student 475 Passed
student 476 Passed
student 477 Passed
student 478 Passed
student 479 Passed
student 480 Passed
student 481 Passed
student 482 Passed
student 483 Passed
student 484 Passed
student 485 Failed
student 486 Passed
student 487 Passed
student 488 Passed
student 489 Passed
student 490 Passed
student 491 Passed
student 492 Passed
student 493 Passed
student 494 Passed
student 495 Passed
student 496 Passed
student 497 Passed
student 498 Passed
student 499 Passed
student 500 Passed
student 501 Passed
student 502 Passed
student 503 Passed
student 504 Passed
student 505 Failed
student 506 Passed
student 507 Passed
student 508 Passed
student 509 Passed
student 510 Passed
student 511 Passed
student 512 Passed
student 513 Passed
student 514 Passed
student 515 Passed
student 516 Passed
student 517 Passed
student 518 Passed
student 519 Passed
student 520 Passed
student 521 Passed
student 522 Passed
student 523 Passed
student 524 Passed
student 525 Passed
student 526 Passed
student 527 Passed
student 528 Failed
student 529 Failed
student 530 Passed
student 531 Passed
student 532 Failed
student 533 Passed
student 534 Passed
student 535 Passed
student 536 Passed
student 537 Passed
student 538 Passed
student 539 Passed
student 540 Passed
student 541 Passed
student 542 Passed
student 543 Passed
student 544 Passed
student 545 Passed
student 546 Passed
student 547 Passed
student 548 Passed
student 549 Passed
student 550 Passed
student 551 Passed
student 552 Passed
student 553 Failed
student 554 Passed
student 555 Passed
student 556 Failed
student 557 Passed
student 558 Passed
student 559 Passed
student 560 Passed
student 561 Passed
student 562 Passed
student 563 Passed
student 564 Passed
student 565 Failed
student 566 Failed
student 567 Passed
student 568 Passed
student 569 Passed
student 570 Passed
student 571 Passed
student 572 Passed
student 573 Passed
student 574 Passed
student 575 Passed
student 576 Failed
student 577 Passed
student 578 Passed
student 579 Failed
student 580 Passed
student 581 Passed
student 582 Passed
student 583 Passed
student 584 Passed
student 585 Passed
student 586 Passed
student 587 Passed
student 588 Failed
student 589 Passed
student 590 Failed
student 591 Passed
student 592 Passed
student 593 Passed
student 594 Passed
student 595 Passed
student 596 Passed
student 597 Failed
student 598 Passed
student 599 Passed
student 600 Passed
student 601 Passed
student 602 Failed
student 603 Passed
student 604 Passed
student 605 Passed
student 606 Passed
student 607 Passed
student 608 Failed
student 609 Passed
student 610 Passed
student 611 Passed
student 612 Passed
student 613 Passed
student 614 Passed
student 615 Passed
student 616 Passed
student 617 Failed
student 618 Passed
student 619 Passed
student 620 Passed
student 621 Failed
student 622 Passed
student 623 Passed
student 624 Passed
student 625 Passed
student 626 Passed
student 627 Passed
student 628 Passed
student 629 Failed
student 630 Failed
student 631 Passed
student 632 Passed
student 633 Passed
student 634 Passed
student 635 Passed
student 636 Passed
student 637 Passed
student 638 Passed
student 639 Passed
student 640 Passed
student 641 Failed
student 642 Passed
student 643 Passed
student 644 Passed
student 645 Passed
student 646 Passed
student 647 Passed
student 648 Passed
student 649 Passed
student 650 Passed
student 651 Passed
student 652 Passed
student 653 Passed
student 654 Passed
student 655 Passed
student 656 Passed
student 657 Passed
student 658 Passed
student 659 Failed
student 660 Passed
student 661 Passed
student 662 Passed
student 663 Passed
student 664 Passed
student 665 Passed
student 666 Passed
student 667 Passed
student 668 Passed
student 669 Passed
student 670 Passed
student 671 Passed
student 672 Passed
student 673 Passed
student 674 Passed
student 675 Passed
student 676 Passed
student 677 Passed
student 678 Passed
student 679 Passed
student 680 Passed
student 681 Passed
student 682 Passed
student 683 Passed
student 684 Failed
student 685 Passed
student 686 Passed
student 687 Passed
student 688 Passed
student 689 Passed
student 690 Passed
student 691 Failed
student 692 Passed
student 693 Passed
student 694 Passed
student 695 Failed
student 696 Passed
student 697 Passed
student 698 Passed
student 699 Passed
student 700 Passed
student 701 Passed
student 702 Passed
student 703 Passed
student 704 Passed
student 705 Passed
student 706 Passed
student 707 Failed
student 708 Passed
student 709 Passed
student 710 Failed
student 711 Passed
student 712 Passed
student 713 Passed
student 714 Passed
student 715 Passed
student 716 Passed
student 717 Passed
student 718 Passed
student 719 Passed
student 720 Passed
student 721 Passed
student 722 Passed
student 723 Passed
student 724 Passed
student 725 Failed
student 726 Passed
student 727 Passed
student 728 Passed
student 729 Passed
student 730 Passed
student 731 Passed
student 732 Passed
student 733 Passed
student 734 Passed
student 735 Passed
student 736 Passed
student 737 Passed
student 738 Passed
student 739 Passed
student 740 Passed
student 741 Passed
student 742 Failed
student 743 Passed
student 744 Passed
student 745 Passed
student 746 Passed
student 747 Passed
student 748 Passed
student 749 Passed
student 750 Passed
student 751 Passed
student 752 Passed
student 753 Passed
student 754 Passed
student 755 Passed
student 756 Passed
student 757 Passed
student 758 Passed
student 759 Passed
student 760 Passed
student 761 Passed
student 762 Failed
student 763 Passed
student 764 Passed
student 765 Passed
student 766 Passed
student 767 Passed
student 768 Passed
student 769 Passed
student 770 Passed
student 771 Passed
student 772 Passed
student 773 Passed
student 774 Passed
student 775 Passed
student 776 Failed
student 777 Passed
student 778 Failed
student 779 Passed
student 780 Passed
student 781 Failed
student 782 Passed
student 783 Passed
student 784 Passed
student 785 Passed
student 786 Failed
student 787 Passed
student 788 Failed
student 789 Passed
student 790 Passed
student 791 Failed
student 792 Passed
student 793 Passed
student 794 Passed
student 795 Failed
student 796 Passed
student 797 Passed
student 798 Passed
student 799 Passed
student 800 Passed
student 801 Passed
student 802 Passed
student 803 Passed
student 804 Passed
student 805 Passed
student 806 Passed
student 807 Passed
student 808 Failed
student 809 Passed
student 810 Passed
student 811 Passed
student 812 Failed
student 813 Passed
student 814 Passed
student 815 Passed
student 816 Passed
student 817 Failed
student 818 Passed
student 819 Passed
student 820 Passed
student 821 Passed
student 822 Passed
student 823 Failed
student 824 Passed
student 825 Failed
student 826 Passed
student 827 Passed
student 828 Passed
student 829 Passed
student 830 Passed
student 831 Passed
student 832 Passed
student 833 Passed
student 834 Passed
student 835 Passed
student 836 Passed
student 837 Passed
student 838 Passed
student 839 Passed
student 840 Passed
student 841 Failed
student 842 Passed
student 843 Failed
student 844 Passed
student 845 Failed
student 846 Passed
student 847 Passed
student 848 Passed
student 849 Passed
student 850 Passed
student 851 Passed
student 852 Passed
student 853 Passed
student 854 Passed
student 855 Passed
student 856 Passed
student 857 Passed
student 858 Passed
student 859 Passed
student 860 Passed
student 861 Passed
student 862 Passed
student 863 Failed
student 864 Passed
student 865 Passed
student 866 Passed
student 867 Passed
student 868 Passed
student 869 Passed
student 870 Failed
student 871 Passed
student 872 Passed
student 873 Passed
student 874 Passed
student 875 Failed
student 876 Passed
student 877 Passed
student 878 Passed
student 879 Passed
student 880 Passed
student 881 Passed
student 882 Passed
student 883 Passed
student 884 Passed
student 885 Passed
student 886 Passed
student 887 Passed
student 888 Passed
student 889 Passed
student 890 Failed
student 891 Passed
student 892 Passed
student 893 Passed
student 894 Passed
student 895 Passed
student 896 Failed
student 897 Failed
student 898 Passed
student 899 Passed
student 900 Passed
student 901 Passed
student 902 Passed
student 903 Failed
student 904 Passed
student 905 Passed
student 906 Passed
student 907 Passed
student 908 Passed
student 909 Passed
student 910 Passed
student 911 Passed
student 912 Passed
student 913 Passed
student 914 Failed
student 915 Failed
student 916 Passed
student 917 Passed
student 918 Failed
student 919 Passed
student 920 Passed
student 921 Passed
student 922 Failed
student 923 Passed
student 924 Passed
student 925 Passed
student 926 Passed
student 927 Passed
student 928 Passed
student 929 Failed
student 930 Failed
student 931 Passed
student 932 Passed
student 933 Passed
student 934 Passed
student 935 Passed
student 936 Passed
student 937 Passed
student 938 Passed
student 939 Passed
student 940 Passed
student 941 Passed
student 942 Passed
student 943 Passed
student 944 Passed
student 945 Passed
student 946 Passed
student 947 Passed
student 948 Failed
student 949 Failed
student 950 Passed
student 951 Passed
student 952 Passed
student 953 Passed
student 954 Passed
student 955 Passed
student 956 Passed
student 957 Passed
student 958 Passed
student 959 Failed
student 960 Passed
student 961 Passed
student 962 Failed
student 963 Passed
student 964 Passed
student 965 Passed
student 966 Passed
student 967 Passed
student 968 Passed
student 969 Passed
student 970 Passed
student 971 Passed
student 972 Passed
student 973 Passed
student 974 Failed
student 975 Passed
student 976 Passed
student 977 Passed
student 978 Passed
student 979 Passed
student 980 Passed
student 981 Failed
student 982 Passed
student 983 Passed
student 984 Passed
student 985 Passed
student 986 Passed
student 987 Failed
student 988 Passed
student 989 Failed
student 990 Passed
student 991 Passed
student 992 Passed
student 993 Passed
student 994 Passed
student 995 Passed
student 996 Passed
student 997 Passed
student 998 Passed
student 999 Passed
student 1000 Passed
Total passed: 865

##### HINTS

In [ ]:
df["math score"].mean()

df[df["math score"] >= 50]

for score in df["math score"]:
    if score >= 50:
        print("Pass")
    else:
        print("Fail")

## INSIGHT GROUP

## 🎯 Goal
Explain what the data means

## 📦 Deliverable
A clear written summary (in markdown)

## Tasks:

👉 Which subject has the highest average?

👉 Which subject is hardest?

👉 What patterns do you notice?

👉 Write your conclusion clearly

# Final Insight

(Write your explanation here in simple terms)

Example:
- Students performed better in reading than math
- Math seems to be the most difficult subject

# ⚒ Team Integration

Now convert important parts into `.py` files in the modules folder

---

## Cleaning → cleaning.py  
## Analysis → analysis.py  

Each group should move useful functions into `.py` files

EXAMPLE

In [ ]:
# analysis.py

def calculate_average(scores):
    return sum(scores) / len(scores)